// Story profiles for every character: who they are, how they think, and why
// they fight. Shown in the Characters screen and when you tap a unit card.
// piece: the chess sigil the Grand Board assigns each fighter.

export const PROFILES = {
  kai: {
    fullName: 'Kai Hinode',
    age: '16',
    from: 'Lowmarket slums, Human Realm',
    piece: 'Pawn',
    quote: 'A pawn that reaches the other side can become anything.',
    personality: 'Loud, reckless and loyal to a fault. Never backs down from a fight — mostly because he’s secretly terrified of being worthless.',
    bio: [
      'A street brawler who fought in back-alley pit matches to keep his little sister Hana fed.',
      'The night before the Grand Gambit, the human team lost a fighter. The proctor grabbed the first kid who could take a punch.',
      'Kai’s fists burn with a fire nobody taught him to control — and he’s starting to wonder where it came from.',
    ],
    style: 'Dive in, hit hard, charge your Ultimate fast. Pair him with Goro so he survives the counter-attack.',
    likes: 'Street noodles, rooftop sunsets, a fair fight',
    dislikes: 'Bullies, waiting, being told to sit down',
  },
  goro: {
    fullName: 'Goro Ishiyama',
    age: '34',
    from: 'Hollowpeak Monastery, the mountain border',
    piece: 'Rook',
    quote: 'Stand behind me. Not beside. Behind.',
    personality: 'Calm, patient and a man of few words, with a bone-dry sense of humor. Big-brother energy toward the whole team.',
    bio: [
      'A temple guardian who held Hollowpeak’s mountain gate alone for fifteen years.',
      'His great shield was carved from that gate after it finally fell — the one day he failed.',
      'He joined the substitute team to protect four kids who have no idea what they’ve walked into.',
    ],
    style: 'Your wall. Plant him at chokepoints like bridges and gates, and nobody gets behind him.',
    likes: 'Green tea, carving tiny stone animals, quiet mornings',
    dislikes: 'Rushing, broken promises, Kai’s cooking',
  },
  rin: {
    fullName: 'Rin Minase',
    age: '15',
    from: 'The Drowned Court, a sunken palace on the Spirit Realm border',
    piece: 'Bishop',
    quote: 'Please hold still. This will only sting a lot.',
    personality: 'Gentle and polite, stubborn underneath. Overthinks everything — until someone she loves is in danger.',
    bio: [
      'The youngest shrine maiden of the Drowned Court, sent to the surface with a sacred water orb that must never run dry.',
      'Her healing tides can close almost any wound.',
      'But every time she uses them, the orb grows a little dimmer — and no one at the Court will tell her why.',
    ],
    style: 'Keep her in the middle of the squad. Her passive heals everyone next to her every turn.',
    likes: 'Rain, seashells, reading way too late',
    dislikes: 'Deserts, lies, people who skip breakfast',
  },
  sora: {
    fullName: 'Sora Kazehara',
    age: '17',
    from: 'The Sky Spire cliffs',
    piece: 'Queen',
    quote: 'Wind’s at my back. Bad news for you.',
    personality: 'Cool, cocky and fiercely competitive. The sharpest tactician on the team, and the worst at admitting she cares.',
    bio: [
      'Sky Spire’s youngest wind-archer — banished after she out-shot, and humiliated, the Spire’s champion in front of the whole court.',
      'She reads a battlefield like a chessboard.',
      'She’s the one who actually plans the team’s moves, while letting Kai think he’s in charge.',
    ],
    style: 'Find high ground (height 2+) for extra range and snipe from behind your front line.',
    likes: 'High places, winning bets, sweet plums',
    dislikes: 'Losing, small rooms, Goro’s lectures',
  },
  nyx: {
    fullName: '“Nyx” (real name unknown)',
    age: 'Unknown — looks about 16',
    from: 'The Umbra, the realm between shadows',
    piece: 'Knight',
    quote: 'Don’t turn your back. …Actually, please do.',
    personality: 'Quiet, mysterious and blunt when she does speak. Endlessly curious about ordinary human things.',
    bio: [
      'She walked into the team’s camp the night before the tournament and said, “I’m on your team now.”',
      'She moves through shadows, strikes from behind, and refuses to explain why she hunts Team Crimson Fang.',
      'Her eyes glow brighter when she lies, so she rarely talks.',
    ],
    style: 'Huge movement — slip around the enemy line and hit from behind for double damage.',
    likes: 'Moonlight, cats, Kai’s terrible jokes (secretly)',
    dislikes: 'Noon sun, crowds, questions',
  },

  varg: {
    fullName: 'Varg Bloodmane, captain of Team Crimson Fang',
    age: '212 (demon years)',
    from: 'The Crimson Wastes, Demon Realm',
    piece: 'King',
    quote: 'Run. It makes the hunt worth something.',
    personality: 'Arrogant and cruel, but honorable to his pack. He respects strength and nothing else.',
    bio: [
      'A three-time Grand Gambit finalist and captain of Team Crimson Fang.',
      'The scar over his eye came from the only fighter who ever beat him, and he has hunted the strong ever since.',
      'Rumor says the Grandmaster himself promised Varg a wish if he crushes the substitute team in Round 1.',
    ],
    style: 'He guards his fortress until you get close. Don’t let him finish off your wounded — each KO heals him.',
    likes: 'The hunt, worthy prey, his pack',
    dislikes: 'Cowards, humans, being made to wait',
  },
  imp: {
    fullName: 'Cinder Imp',
    age: 'About 3 (they grow up fast)',
    from: 'The Ember Wastes',
    piece: 'Pawn',
    quote: 'Hee hee! Burn, burn, BURN!',
    personality: 'Giggly, greedy and easily distracted by anything shiny.',
    bio: [
      'Fire imps hatched in the lava pools of the Ember Wastes.',
      'Weak on their own, but deadly in a crowd — they lob fireballs from walls and hide in lava where no one can follow.',
    ],
    style: 'Fragile. Close the distance fast, or hit them with Tide attacks.',
    likes: 'Shiny things, explosions, lava baths',
    dislikes: 'Water, being stepped on',
  },
  brute: {
    fullName: 'Bog Brute',
    age: 'Older than the swamp it came from',
    from: 'The Mirewood marshes',
    piece: 'Rook',
    quote: '…glorp.',
    personality: 'Slow, stubborn and surprisingly gentle with frogs.',
    bio: [
      'A living heap of swamp mud that sprouts a new lily flower every time it wins a fight.',
      'Arrows and spells sink into its body like stones into a bog.',
    ],
    style: 'Shrugs off ranged hits. Beat it up close — Goro’s Stone attacks are super effective.',
    likes: 'Rain, frogs, standing very still',
    dislikes: 'Fire, droughts, being rushed',
  },
  gargoyle: {
    fullName: 'Fortress Gargoyle',
    age: 'Carved 600 years ago',
    from: 'The walls of Varg’s fortress',
    piece: 'Knight',
    quote: '*grinding stone noises*',
    personality: 'Silent, tireless and very territorial.',
    bio: [
      'Statues carved to guard the arena fortress, woken by demon magic for the tournament.',
      'They dive from above, cross rivers on stone wings, and never sleep.',
    ],
    style: 'Fast fliers that dive at your backline. Keep Rin and Sora covered and hit them with Gale attacks.',
    likes: 'High ledges, the night',
    dislikes: 'Pigeons, Gale magic',
  },
};
